### ISSUE TITLE
菜单栏图标在暗色菜单栏上看不到

### ISSUE THREAD

**Issue by xream** [klesh/fu#1]
在使用两台显示器的情况下, 焦点在显示器1时, 菜单栏图标出现在显示器2. 反之同理.

**Comment by klesh** [comment]
请问你的 OS X 是什么版本的？
我的也是2台显示器的。

**Comment by xream** [comment]
10.12.3 (16D32)

2017-02-05 11:24 GMT+08:00, Klesh Wong <notifications@github.com>:

**Comment by klesh** [comment]
这真是奇怪，和我的版本一样。照理是2边都会出现才对。有没有办法可以提供图片？我怕理解错。

**Comment by xream** [comment]
焦点在显示器1:

![image](https://cloud.githubusercontent.com/assets/1210282/22623452/942f0eaa-eb96-11e6-8a78-c229ef9df614.png)

图标在显示器2:

![image](https://cloud.githubusercontent.com/assets/1210282/22623453/9e45f73c-eb96-11e6-8341-e883037c4d70.png)

我装了 Bartender 2, 但是退出之后还是这样. 如果是有冲突也应该不需要卸载吧.

**Comment by xream** [comment]
发现截图里看不到图标...在dropbox左边的左边那个空位...

**Comment by xream** [comment]
我知道了...我用了暗色菜单栏 你的图标颜色看不到了...

**Comment by klesh** [comment]
嗯，是的。看到图片就明白了。是图标的问题。

**Comment by klesh** [comment]
已更新图标
https://github.com/klesh/fu/releases/tag/v1.0.1
