### ISSUE TITLE
win图片文件名含有中文上传失败

### ISSUE THREAD

**Issue by lilyomo** [klesh/fu#10]
windows版本，1.3.1
运行环境：win7
如果图片文件名含有中文，上传失败。

**Comment by klesh** [comment]
可能是刚好网络问题？或者文件太大？我这边无法重现
![image](https://user-images.githubusercontent.com/61080/36930634-3577d9f4-1ee0-11e8-93d1-678772d5a0c6.png)

**Comment by lilyomo** [comment]
嗯，是的，应该是文件过大了。
