### ISSUE TITLE
可以添加多选保存吗

### ISSUE THREAD

**Issue by Leezj9671** [klesh/fu#11]
比如我同时想上传到sm.ms，同时本地也保存，可否将勾选框改成多选？

**Comment by klesh** [comment]
我不太明白你的意思？

**Comment by Leezj9671** [comment]
在Servers功能里我有sm.ms和local两个选项，我想同时启用，使我可以将图片上传到sm.ms的同时也保存到本地，希望能做出这个功能~

**Comment by klesh** [comment]
2.0 已经支持这个功能了。
