### ISSUE TITLE
Upload fail: Couldn't resolve host name

### ISSUE THREAD

**Issue by rosuH** [klesh/fu#12]
## OS：
Windows 10 x64 pro 1709

## Software Version
1.3.1

## Issues
配置又拍云存储，使用 sFTP 和 FTP 都无法正常上传：

- 使用 sFTP

点击上传之后会一直显示上传状态（任务栏图标为一个箭头），等很久也没有反应。

- 使用 FTP

点击上传之后出错，提示为：

> Upload fail: Couldn't resolve host name

##  配置如下

![Snipaste_2018-03-07_23-06-32.png](https://i.loli.net/2018/03/07/5aa00018c7bb3.png)

## 其他
在同样的服务器配置，同等网络情况下：

- 可以用 FileZilla 登陆又拍云服务器，并正常操作
- 使用 sm.ms 可以正常上传图片

- - - - -
感谢~

**Comment by klesh** [comment]
可以用 ip 试下吗？

**Comment by rosuH** [comment]
使用 ip 之后，sFTP 和 FTP 均在进行长时间的上传尝试后抛出错误：

![Snipaste_2018-03-10_10-51-11.png](https://i.loli.net/2018/03/10/5aa3488a82470.png)

**Comment by rosuH** [comment]
@klesh  使用 ip 之后，sFTP 和 FTP 均在进行长时间的上传尝试后抛出错误：

![Snipaste_2018-03-10_10-51-11.png](https://i.loli.net/2018/03/10/5aa3488a82470.png)

**Comment by klesh** [comment]
这些错误信息看起来像是网络问题，请用第三方的 ftp 软件如 filezilla 试下能不能连上 ftp 先。
另外 sftp 和 ftp 虽然只差一个字，但却是完全没有关系的两种协议。所以不要用 sftp 尝试去连只支持 ftp 的服务器。

抱歉这么久才回复。

**Comment by rosuH** [comment]
@klesh 感谢回复。刚刚重新下载尝试了一下，依旧无法使用，FTP 模式下抛出错误：`Upload fail: Couldn't resolve host name`。

我使用 Filezilla  是没有问题的（同样是 FTP），主机是又拍云的`v0.ftp.upyun.com`。

**Comment by klesh** [comment]
有使用ss之类的工具吗？

**Comment by rosuH** [comment]
关掉后也不行。

**Comment by klesh** [comment]
是否方便提供一个临时帐号我试下是否能复现？

**Comment by rosuH** [comment]
@klesh 您 Gmail 查收一下。

**Comment by klesh** [comment]
![image](https://user-images.githubusercontent.com/61080/41219002-93297bfe-6d8f-11e8-8ced-dd99aa36d5b6.png)
提示的是 login denied，说明我这边域名是可以正常解析的。问题应该还是出现在你机器上的代理设置上，请检查一下环境变量？

**Comment by rosuH** [comment]
这个提示我没有遇到过。我刚刚使用 FileZilla  登陆该账号是没有问题的。
至于代理的问题，我的系统刚好是前几天重装过了，关闭了 SS 之后应该不会有其他软件干扰。环境变量也看不出什么问题。

**Comment by rosuH** [comment]
@klesh 您自己用过又拍云存储吗？会不会是又拍云的问题？

**Comment by klesh** [comment]
我没有用过。。。看起来不像是又拍云的问题。
1. 显示 can not resolve host 表示是解析域名的时候失败，但你使用 filezilla 又可以正常连上去，这个太谜了。
2. 我这边测试的结果是可以连上 ftp ，但显示登录失败（应该是用户名的问题）
![image](https://user-images.githubusercontent.com/61080/41223306-0344bb36-6d9c-11e8-922a-1e158634ca39.png)
我使用的是 libcurl ，有可能受到系统环境变量如 ftp_proxy  http_proxy https_proxy socks_proxy 之类设定的影响，不过 proxy 不应该影响到 dns 解析才对。太谜了。

**Comment by rosuH** [comment]
FTP 那个确实是用户名问题，格式是用户名+服务名

![image](https://user-images.githubusercontent.com/15865017/41225414-4cd78364-6da1-11e8-94a8-9e1cbb7e397a.png)


环境变量也没有您提及的那几个😂

**Comment by yiranzai** [comment]
@rosuH 我遇到了和你一样的问题,请问你解决了吗?

**Comment by rosuH** [comment]
@yiranzai 没有😂

**Comment by yiranzai** [comment]
@rosuH wow.我放弃了,我选择使用[shareX](https://getsharex.com/)
