### ISSUE TITLE
sm.ms上传报这个错是什么意思

### ISSUE THREAD

**Issue by monkey000** [klesh/fu#15]
![snipaste_2018-04-19_11-45-03](https://user-images.githubusercontent.com/36021889/38970323-601cafde-43c7-11e8-82dd-668aa3582475.png)

**Comment by wjingyuan** [comment]
我今天使用也是，突然爆出这个错误。

![image](https://user-images.githubusercontent.com/28554380/41191008-29e15db2-6c1b-11e8-900c-c68602e35593.png)

<img width="318" alt="snipaste_20180609_192409" src="https://user-images.githubusercontent.com/28554380/41190999-08fdf98e-6c1b-11e8-8bd7-71cf4c43ab9d.png">

**Comment by klesh** [comment]
看起来是图像文件读取失败的样子，是复制文件然后上传的吗？

**Comment by wjingyuan** [comment]
对的，用snipaste截屏后，单击fu，然后单击copy，以前没问题。但是昨天一开始还行，后来不知道为何就开始报错。

然后我试着先截屏保存到桌面，然后打开图片，右键单击复制-->单击fu-->单击copy，还是不行。

**Comment by klesh** [comment]
全路径和图片源文件都请给一下，我看看能不能复现

**Comment by wjingyuan** [comment]
我刚才随便传的这张图片，同样显示失败。
![image](https://user-images.githubusercontent.com/28554380/41215137-7db9cce6-6d81-11e8-97a1-c07f570cf6a8.png)
![image](https://user-images.githubusercontent.com/28554380/41215141-82c10542-6d81-11e8-8e8b-c0f59fed55bc.png)
![image](https://user-images.githubusercontent.com/28554380/41215150-88e003ec-6d81-11e8-9d0c-7aba1ed46b59.png)

**Comment by klesh** [comment]
你这个信息提示的是成功？

**Comment by wjingyuan** [comment]
尴尬了，截图后看fu的图标是一个向上的箭头，上次出现问题，那个图标就一直是向上箭头，所以没注意看提示是成功上传。

刚才我又试了下，复制第三张图片时才提示错误，前两张正常上传。上次我出错情况类似：刚开始正常使用，后面就一直提示出错。

刚才实验出错的图片以及出错截图如下：

![image](https://user-images.githubusercontent.com/28554380/41219218-3b58bf9c-6d90-11e8-9e64-0188ebe16450.png)

![image](https://user-images.githubusercontent.com/28554380/41219222-3f0c0ac2-6d90-11e8-8568-472cc9a688e8.png)

**Comment by klesh** [comment]
同一张吗？出错那张有什么特别之处吗？比如说比较大？
我试着边续上传5~6张相同的，也没能复现你说的问题。

**Comment by wjingyuan** [comment]
不是。

![image](https://user-images.githubusercontent.com/28554380/41225015-6a8848cc-6da0-11e8-88c2-0ebf5dfe4264.png)

我文件夹里有这么几张图片，我随意上传，前面2张都正常上传，上传第3张时就报错了。

第三张图片也没什么特殊的地方。

比如上面的截图中，第一张图片，今天试验时就正常上传，但是前几天他就上传失败。

**Comment by klesh** [comment]
按照你说的情况，结合错误信息，是网络的问题，在接受服务器返回信息时发生错误。比如说，有可能是网络中某个节点在超过一定数据量之后开始随机扔掉包？

**Comment by wjingyuan** [comment]
这种问题以前没出现过，也不是我一个人出现。有什么办法解决吗？

**Comment by klesh** [comment]
sm.ms 改好之后又会被 ban 。已经放弃支持。
