### ISSUE TITLE
希望能增加按月份文件夹上传图片

### ISSUE THREAD

**Issue by loveshizuka** [klesh/fu#17]
软件很棒，非常合我的心意，感谢！
现在软件的ftp上传设置可以按日期创建文件夹进行组织，但不能按月份，希望软件能增加一个按月份进行组织图片的选项。比如，上传一张图片后，自动新建2018-11的文件夹，当月的图片上传在其中。如果能实现就最好了。望考虑建议，非常感谢！

**Comment by klesh** [comment]
v2 已支持
