### ISSUE TITLE
总在上传时出现这个警告，如何避免呢？

### ISSUE THREAD

**Issue by loveshizuka** [klesh/fu#18]
用的FTP上传，已设置的选项有：图片压缩，水印（水印图片文件名有中文），使用markdown格式输出。在复制图片，点击要上传的图片后，总会弹出这个警告对话框，是啥意思，要如何避免呢？谢谢！
![20181110213110](https://user-images.githubusercontent.com/25612355/48301949-96715200-e530-11e8-80df-f9ccbd2fd6f2.png)

**Comment by klesh** [comment]
这个看起来是图片本身有问题，载入失败了。应该不是文件名引起的，可以提供图片样张吗？

**Comment by klesh** [comment]
wxWidget 的问题。 v2 使用了 qt 。不会弹出警告了
