### ISSUE TITLE
请问可以添加导出功能吗？

### ISSUE THREAD

**Issue by mangococo** [klesh/fu#19]
希望可以增添导出备份的功能，不然一旦卸载重装之前的图基本就成了“太空垃圾“了。

**Comment by klesh** [comment]
抱歉，不知什么原因。没有收到邮件通知。
备份的话，可以直接将以下文件夹直接复制出来。重装之后再恢复到原来的位置即可：

Windows:  %APPDATA%/fu
Linux/Mac: 应该是  ~/.config/fu

**Comment by mangococo** [comment]
谢谢回复，明白了
