### ISSUE TITLE
请问macOS下面如何编译？

### ISSUE THREAD

**Issue by taozhijiang** [klesh/fu#20]
自己想修改增加一些feature，比如根据文件内容散列值得到新的文件名等功能。
但是在macOS下面编译失败。

所以请教在macOS下面编译安装的方法。
谢谢。

CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /Users/taozj/Downloads/fu-1.3.1/missing aclocal-1.15
 cd . && /bin/sh /Users/taozj/Downloads/fu-1.3.1/missing automake-1.15 --gnu
configure.ac: error: no proper invocation of AM_INIT_AUTOMAKE was found.
configure.ac: You should verify that configure.ac invokes AM_INIT_AUTOMAKE,
configure.ac: that aclocal.m4 is present in the top-level directory,
configure.ac: and that aclocal.m4 was recently regenerated (using aclocal)
automake-1.15: error: no 'Makefile.am' found for any configure output
automake-1.15: Did you forget AC_CONFIG_FILES([Makefile]) in configure.ac?
make: *** [Makefile.in] Error 1

**Comment by klesh** [comment]
这个看起来是需要装个 automake 。
