### ISSUE TITLE
您好！打扰您了，我编译时找不到qcurl.h。

### ISSUE THREAD

**Issue by hitomiyyds** [klesh/fu#25]
您好，我编译时找不到qcurl.h。后来看到：
![](http://139.196.101.101/pic/2020-04-20/20200420163322.png)
可我找不到libqcurl,只有libcurl，头文件也只有curl.h，不是qcurl.h。
可以教教我吗？我现在windows和mac下都运行一遍，麻烦您了！

**Comment by klesh** [comment]
是我的错，忘了链接上 qcurl 了

https://github.com/klesh/libqcurl

**Comment by hitomiyyds** [comment]
谢谢！
