### ISSUE TITLE
配置项， “输出格式” 添加并保存新格式 提示错误 “Format with the same name already exists.”

### ISSUE THREAD

**Issue by TrekMax** [klesh/fu#27]
fu 作者大大你好：
 
我在使用 fu 过程中遇到一些 bug，对于 fu 的源码没有详细了解过，特在 issue 求助，感谢🙇‍ 作者大大做出这么好用的软件。
具体问题如下：

使用环境： Windows 10 v20H2, fu v2.0.1

现象：打开配置项， 在 “输出格式” 添加新格式 ，并点击保存是，提示错误 “Format with the same name already exists.”
![image](https://user-images.githubusercontent.com/25558596/90309333-52d42500-df1a-11ea-8253-c1583dd22ecd.png)

如需复现, 可以联系我的邮箱📫： qinyun575@foxmail.com
====
感谢！

**Comment by klesh** [comment]
谢谢反馈，已经修复。
更新传送门： https://github.com/klesh/fu/releases/tag/v2.0.2

**Comment by TrekMax** [comment]
问题已解决，感谢🙇‍！
