### ISSUE TITLE
1.1.0, macOS版本下载链接404

### ISSUE THREAD

**Issue by KrabsWong** [klesh/fu#3]
[macOS v1.1.0](https://github.com/klesh/fu/blob/master/download/fu-v1.1.0-osx.dmg) 链接404

**Comment by klesh** [comment]
已更新链接：https://github.com/klesh/fu/raw/f1ed9eafc34c360b4f1bec29496bfb5bdaa44634/download/fu-v1.1.0-osx.dmg
