### ISSUE TITLE
能否考虑在软件内加个 About？

### ISSUE THREAD

**Issue by rosuH** [klesh/fu#5]
## 软件很好用！感谢！
最初在 V2 看到，然后一直用很久。前几天想看看这软件有没有更新，然而软件界面连个“关于”的菜单都没有？

也不知道去哪寻官方地址了。才又在 V2 搜了几页才找到啊。

作者能否考虑在软件内加个主页或项目的链接？这样比较好找。

**Comment by klesh** [comment]
可以，最近比较忙，要迟些才能更新。
