### ISSUE TITLE
Can not built on Ubuntu 16.04 

### ISSUE THREAD

**Issue by RoadToDream** [klesh/fu#6]
[errcode.txt](https://github.com/klesh/fu/files/924072/errcode.txt)
Have installed the necessary packages

**Comment by klesh** [comment]
can I have your g++ version?
please run following command to get those info:
g++ -v

**Comment by RoadToDream** [comment]
`Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.4' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 
`
here it is and thank you very much

**Comment by klesh** [comment]
Hi, I have published a new version, you may like to try it out, I had it tested on Ubuntu 16.10 and Linux Mint 18.1, let me know if any thing go south. Thanks

**Comment by RoadToDream** [comment]
I tried and finally decide not to compile
It depends on so many packages that are not compatible with the system, and some of the packages are related to primus. I don't want to affects my discrete GPU. Sorry for that.
