### ISSUE TITLE
Win10 无法启动

### ISSUE THREAD

**Issue by Amos-li** [klesh/fu#8]
---------------------------
fu.exe - 应用程序错误
---------------------------
应用程序无法正常启动(0xc000007b)。请单击“确定”关闭应用程序。 
---------------------------
确定   
---------------------------

**Comment by klesh** [comment]
下载的是什么版本? windows 10 版本是什么？我试了v1.3.1的，可以正常启动。

**Comment by Amos-li** [comment]
`1.2.0` 和 `1.3.1` 我都尝试了! 都无法启动的.  win10专业版  **winver** 查看 版本1709(OS内部版本 16299.248 )

**Comment by klesh** [comment]
好奇怪，跟我一样的版本。方便截个屏看下吗？

**Comment by Amos-li** [comment]
不好意思, 前段时间比较忙! 没有顾得上. 刚才试了最新版这个问题已经解决,
