### ISSUE TITLE
不会用

### ISSUE THREAD

**Issue by wjingyuan** [klesh/fu#9]
好尴尬，下载下来了，不知道怎么启动，不知道怎么使用。

**Comment by klesh** [comment]
# 以 windows 为例
解压，双击 fu.exe 运行 ，右下角任务栏会出现图标。
这时，复制图片，或截屏后，右面任务栏图标，再点击 pending 那里的图片（或截屏），就会开始上传。
上传成功后会有提示，相应的网址或markdown代码也会相应地放到剪贴板里，此时，到你想粘贴的地方按 ctrl + v 就可以了

**Comment by wjingyuan** [comment]
奇怪了，我直接下的zip，解压后没看到exe文件

**Comment by wjingyuan** [comment]
![image](https://user-images.githubusercontent.com/28554380/36784298-dcae98e4-1cb9-11e8-959a-bab4ae3b7461.png)

**Comment by klesh** [comment]
在这里下：https://github.com/klesh/fu/releases

**Comment by klesh** [comment]
下载 fu-v1.3.1-win32.7z

**Comment by wjingyuan** [comment]
有没有百度云链接或者QQ群之类的，直接从GitHub上下载好慢

**Comment by FrankHan** [comment]
@klesh 我是64位windows7，双击fu.exe提示
 计算机中丢失vcruntime140.dll
，请问是不支持64位或者win7吗？

**Comment by klesh** [comment]
@FrankHan 需要安装 vc++ 运行时。 https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by FrankHan** [comment]
@klesh 我昨天装了，装了之后又提示缺少别的dll，我自己研究一下吧，如果研究清楚了，我会在这里回复。

**Comment by klesh** [comment]
@FrankHan 我试了下，需要装 x86 版的运行时。

**Comment by FrankHan** [comment]
@klesh  好的，我回来看下
